
# SEO settings
title: tweedge's blog
description: "A security engineer's blog about his projects, research, philosophy, and career."
keywords: "cybersecurity, hacking, software engineering, best practices, research, web, technology"
url: https://chris.partridge.tech
repo: https://github.com/partridge-tech/chris-blog

# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

source: .
destination: public

# Sass configuration
sass:
  sass_dir: scss
  style: compressed # expanded

# Author settings
author:
  name     : Chris Partridge
  job      : Security Engineer
  bio      : "I do cybersecurity things with a focus on effective software security and internet-scale research."
  thumb    : /images/profile.png
  email    : chris@partridge.tech
  url      : https://chris.partridge.tech
  github   : https://github.com/tweedge
  gitlab   : https://gitlab.com/tweedge
  twitter  : https://twitter.com/_tweedge
  facebook : https://facebook.com/tweedge
  linkedin : https://linkedin.com/in/tweedge

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@_tweedge"

gems:
  - bourbon
  - jekyll-paginate-v2
  - jekyll-target-blank

# do not publish
exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "workers-site", "wrangler.toml", "LICENSE", "scss"]

# collections
collections:
  content:
    output: true
    permalink: /:path/

# pagination v2 settings
pagination:
  enabled: true
  debug: true
  collection: 'content'
  per_page: 5
  sort_reverse: true
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
