# The name of your Workers application
name = "landing-chris"

# Your Cloudflare account ID
account_id = "583a61916394f22ed8f17c5734e3c970"

# The kind of application you're deploying to Cloudflare
type = "webpack"

# Publish to workers.dev by default
workers_dev = true
