name = "landing-chris"
type = "webpack"
account_id = "583a61916394f22ed8f17c5734e3c970"
workers_dev = false
route = "chris.partridge.tech/*"
zone_id = "36b12e0ec5729dabd2578243ec77a007"

[site]
bucket = "./public"
entry-point = "workers-site"
